### PR TITLE
make messages go to correct place

### LINKED ISSUE #79: Message Batching can send messages to the wrong user.
As reported in https://github.com/uProxy/uproxy/issues/764, The batching code currently uses a single queue, rather than keeping messages split out to their appropriate destination.  This is bad.

### PR DESCRIPTION
**Pull request by willscott**
Fix #79

### CODE REVIEW

File: src/core/socialprovider.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ var XMPPSocialProvider = function(dispatchEvent) {
   // rate limiting).
   this.sendMessagesTimeout = null;
   this.timeOfFirstMessageInBatch = 0;
-  this.messages = [];
+  this.messages = {};
```
Comment (iislucas) [inline src/core/socialprovider.js]: I'd add a comment to let the reader know what the type/structure is of messages. Namely that `this.messages` is indexed by `clientId`'s, and each value is an array of strings that are the (XML-escaped? or is that done in `client.send`?) messages to sent to that client-id.

**Comment by iislucas** [comment]
thanks for the fast fix! LGTM (although @dborkan is probably the most familiar with that, so maybe good for him to have a read too)

File: spec/socialprovider.spec.js [hunk 2]
```diff
@@ -102,6 +102,19 @@ describe("Tests for message batching in Social provider", function() {
...
 
+  it("sends message to correct destinations", function() {
+    xmppSocialProvider.sendMessage('Bob', 'Hi', function() {});
+    xmppSocialProvider.sendMessage('Alice', 'Hi', function() {});
+    expect(xmppSocialProvider.client.send).not.toHaveBeenCalled();
+    jasmine.clock().tick(100);
+    expect(xmppSocialProvider.client.send.calls.count()).toEqual(2);
+    var dest = xmppSocialProvider.client.send.calls.first().args[0].parent.attrs.to;
+    if (dest !== 'Bob' && dest !== 'Alice') {
+      expect(dest).toEqual('Bob');
```
Comment (dborkan) [inline spec/socialprovider.spec.js]: I'm a little confused by this test case.  Won't this ```expect(dest).toEqual('Bob');``` fail, since this statement is only hit if dest !== 'Bob' as per the above if statement?

**Comment by dborkan** [comment]
Just the question on the test, otherwise :+1: - thanks for working on this!

File: spec/socialprovider.spec.js (hunk 2 above)
Comment (willscott) [inline spec/socialprovider.spec.js]: Yeah - this is expressing that it either needs to be 'bob' or 'alice', since the messages can be reordered depending on how object keys are implemented.  There isn't a direct jasmine way to say .toEqual('bob' or 'alice'), so If it isn't one of the two I want it to fail.  better way to express that?

Comment (dborkan) [inline spec/socialprovider.spec.js]: Not sure - if you throw an exception with a string "Expected dest to be Bob or Alice but <dest>", would that show up in the console as that 1 test case failing?  Or would it break all later test cases as well?

Comment (willscott) [inline spec/socialprovider.spec.js]: I think it would show up at the end of the jasmine run as 'an error was
encountered', but not fail the given test case, due to issues with
accounting for asynchronicity.

Comment (dborkan) [inline spec/socialprovider.spec.js]: OK, this code is fine then, but can you add a comment explaining that your  ```expect(dest).toEqual('Bob');``` is intended to fail as dest should have been 'Bob' or 'Alice'?

Comment (willscott) [inline spec/socialprovider.spec.js]: done.

File: src/core/socialprovider.js (hunk 1 above)
Comment (willscott) [inline src/core/socialprovider.js]: done.

**Comment by dborkan** [comment]
:+1:

File: src/core/socialprovider.js [hunk 3]
```diff
@@ -233,44 +234,46 @@ XMPPSocialProvider.prototype.sendMessage = function(to, msg, continuation) {
...
+            (this.vCardStore.getClient(to).status === 'ONLINE') ?
+                'normal' : 'chat';
+
+        try {
+          this.client.send(new window.XMPP.Element('message', {
+            to: to,
+            type: messageType
+          }).c('body').t(JSON.stringify(this.messages[to])));
+        } catch(e) {
+          this.logger.warn(e.message);
```
Comment (dborkan) [inline src/core/socialprovider.js]: Right now sendMessage is always invoking continuation() (success) regardless of whether or not we catch an error from this.client.send.

Do you think it would be better to only invoke continuation() if we don't catch any error from this.client.send?  Or would this be bad because it could potentially delay continuation by up to 2.1 seconds?  Currently there is no way for callers of sendMessage to detect an error

Comment (willscott) [inline src/core/socialprovider.js]: I guess the question I had when doing this is whether this is the right
place to do the batching, or whether this is something that should be done
more generally at the uProxy level, and the XMPP provider should
immediately send the batch when it gets it. thoughts?

Comment (dborkan) [inline src/core/socialprovider.js]: I think it should be in freedom-social-xmpp, because the batching logic
will probably differ in each social network - some may not need batching at
all, some might have very strict limits.

Comment (dborkan) [inline src/core/socialprovider.js]: More specifically - the reason we added batching is because we saw that
GTalk was giving us 503 errors if we sent too many messages (around 10 per
second seemed to trigger this) to the same user in a row (not sure what
happens if we send to different users).  It seems probable that other
social networks would have a different threshold

Comment (willscott) [inline src/core/socialprovider.js]: Yeah, no, you're right - i had forgotten how this was implemented and was worrying about a noticeable delay on sent messages.  I'm still not sure if you always want to json stringify sent messages in an array (like if they're interactive chat messages with another person). but batching when lots of messages get sent at once makes sense.

as for continuation, if we're batching we'd either need to store the continuations in the messages buffer until they're actually sent, or just proactively say done.  The worry if we don't proactively say done is that clients will wait for them to get sent, so you'll end up just rate limiting the client to 1 message / .1 seconds and never actually get batches.
Thoughts?

Comment (dborkan) [inline src/core/socialprovider.js]: Currently uProxy ignores the return promise from sendMessage, so this pull request should be fine for now.  But going forward I think uProxy will want to either automatically retry failed message, or display an error to the user - to do that I think we need to know whether the message really sent and so we'd need to store the continuation.

Also in that case, I think uProxy code should assume the message would be sent async, and not any rate limiting by waiting for the sendMessage promise to fulfill, i.e. we would only need to handle the sendMessage error case, not success.

For now though this code is fine, maybe just put a TODO?

**Comment by willscott** [comment]
Updated to delay callbacks until message sent, and deal with #77 the right way. PTAL

File: src/core/socialprovider.js [hunk 4]
```diff
@@ -45,7 +45,8 @@ var XMPPSocialProvider = function(dispatchEvent) {
   // rate limiting).
   this.sendMessagesTimeout = null;
   this.timeOfFirstMessageInBatch = 0;
-  this.messages = [];
+  // buffered outbound messages, arrays of messages keyed by recipient.
```
Comment (dborkan) [inline src/core/socialprovider.js]: Can you update this now to say that this.messages is a mapping from recipient to message/continuation pair?

File: src/core/socialprovider.js [hunk 5]
```diff
@@ -233,46 +234,74 @@ XMPPSocialProvider.prototype.sendMessage = function(to, msg, continuation) {
...
+        var i = 0,
+          messageType =
+            (this.vCardStore.getClient(to).status === 'ONLINE') ?
+                'normal' : 'chat',
+          message = new window.XMPP.Element('message', {
+            to: to,
+            type: messageType
+          }).c('body'),
+          body;
+        if (messageType === 'normal') {
```
Comment (dborkan) [inline src/core/socialprovider.js]: Might be good to add comments here saying that for 'normal' messages we are sending them as a JSON formatted array, while for 'chat' messages we are concatenating them to a '\n' separated string.

**Comment by dborkan** [comment]
Just a few requests for comments, otherwise :+1: , thanks!
